server:
  port: 8081

spring:
  application:
    name: mod-ebsconet
  cloud:
    openfeign:
      okhttp:
        enabled: true

  liquibase:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  jackson:
    default-property-inclusion: non_null

feign:
  client:
    config:
      change-manager:
        logger-level: full

management:
  endpoints:
    web:
      base-path: "/admin"

header:
  validation:
    x-okapi-tenant:
      exclude:
        base-paths: "/admin"
