openapi: 3.0.0
info:
  title: Ebsconet integration API
  description: "Ebsconet integration API"
  version: 0.0.1
servers:
  - url: /ebsconet/
paths:
  /validate:
    description: Validation API
    get:
      summary: Validate
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/validationResponse"
      operationId: getValidation
  /orders/order-lines/{poLineNumber}:
    description: Orders API
    get:
      summary: Get single Ebsconet product order line
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ebsconetOrderLine"
        '400':
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the error (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              example:
                $ref: "#/components/examples/error"
              schema:
                $ref: "#/components/schemas/error"
        '404':
          description: Purchase order line with a given number not found
          content:
            application/json:
              example:
                $ref: "#/components/examples/error"
              schema:
                $ref: "#/components/schemas/error"
        '500':
          description: Internal server error, e.g. due to misconfiguration
          content:
            application/json:
              example:
                $ref: "#/components/examples/error"
              schema:
                $ref: "#/components/schemas/error"
      operationId: getEbsconetOrderLine
      parameters:
        - name: poLineNumber
          in: path
          description: product order line number
          required: true
          schema:
            $ref: "#/components/schemas/poLineNumber"
    put:
      summary: Save single Ebsconet product order line
      responses:
        '200':
          description: OK
        '400':
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the error (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              example:
                $ref: "#/components/examples/error"
              schema:
                $ref: "#/components/schemas/error"
        '500':
          description: Internal server error, e.g. due to misconfiguration
          content:
            application/json:
              example:
                $ref: "#/components/examples/error"
              schema:
                $ref: "#/components/schemas/error"
      operationId: putEbsconetOrderLine
      parameters:
        - name: poLineNumber
          in: path
          description: product order line number
          required: true
          schema:
            $ref: "#/components/schemas/poLineNumber"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ebsconetOrderLine"
        required: true
components:
  schemas:
    ebsconetOrderLine:
      $ref: schemas/mod-ebsconet/ebsconet_order_line.json
    poLineNumber:
      $ref: schemas/mod-orders/order_line_number.json
    organization:
      $ref: schemas/mod-orgs/organization.json
    poLine:
      $ref: schemas/mod-orders/po_line.json
    poLineCollection:
      $ref: schemas/mod-orders/po_line_collection.json
    expenseClassCollection:
      $ref: schemas/mod-finance/expense_class_collection.json
    fundCollection:
      $ref: schemas/mod-finance/fund_collection.json
    purchaseOrder:
      $ref: schemas/mod-orders/purchase_order.json
    validationResponse:
      $ref: schemas/mod-orders/validation_response.json
    compositePoLine:
      $ref: schemas/mod-orders/composite_po_line.json
    note:
      $ref: schemas/mod-notes/note.json
    noteCollection:
        $ref: schemas/mod-notes/note_collection.json
    error:
      $ref: schemas/common/error.json#/Error
    errors:
      $ref: schemas/common/errors.json
    uuid:
      $ref: schemas/common/uuid.json
  examples:
    error:
      value:
        $ref: examples/error.sample
